### ISSUE TITLE
Meters does not show the power consumption of the Heat Pump

### ISSUE THREAD

**Issue by MysteriousStudent** [tum-ewk/HAMLET#84]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of HAMLET.

### Reproducible example

```python

```

### Issue description

Meters doesnt show the power consumption of the Heat Pump. The Meters.ft file which is one of the Results form the Executor doesnt provide the power consumption of the heat pump

### Expected behavior

Meters show the power consumption of the Heat Pump.

**Comment by TUM-Doepfert** [comment]
Currently recording of values is limited to one per meter ID. Needs to be extended so that several energy types can be recorded per meter.
